
FROM eigen3:latest AS eigen3

FROM ubuntu:22.04 AS eigen3_hello_world



ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y g++ make cmake git catch2 && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /tmp/eigen3_hello_world
WORKDIR /tmp/eigen3_hello_world
COPY . . 


COPY --from=eigen3 /tmp/eigen3 /tmp/eigen3 
WORKDIR /tmp/eigen3/build
RUN make install



WORKDIR /tmp/eigen3_hello_world
RUN mkdir -p build && \
    cd build && \
    cmake .. && \
    make
